apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    humanitec.com/orgId: ${{ values.orgId | dump }}
    humanitec.com/appId: ${{ values.name | dump }}
    quay.io/repository-slug: ${{ values.quay_destination | dump }}
    backstage.io/kubernetes-id: ${{values.name}}
    backstage.io/source-location: url:https://${{values.githost}}/${{values.destination}}
    github.com/project-slug: ${{values.destination}}
  tags:
    - node
    - humanitec
spec:
  type: service
  owner: ${{values.owner | dump}}
  lifecycle: experimental
  providesApis:
    - ${{values.name | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.name | dump}}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  definition:
    $text: ./openapi.yaml
